development:
  bucket: startupcogs-dev
  access_key_id: AKIAIM23HXBZ4YZNM24Q
  secret_access_key: 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
production:
  bucket: startupcogs-pro
  access_key_id: AKIAIM23HXBZ4YZNM24Q
  secret_access_key: klCxyVDazK4oBr2X1oBPsw4FvxEAPdS9
test:
  bucket: startupcogs-dev
  access_key_id: AKIAIM23HXBZ4YZNM24Q
  secret_access_key: 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
